trigger:
- main   #git main branch for code

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: ''  #App Name is Azure 
  azureSubscription: ''
  packageDir: '.'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
    - job: 'Build'
      displayName: 'Build Nodejs api'
    steps:
      - task : UserNode@2
        displayName: 'Use Nodejs latest version'
        inputs: 
          versionSpec: 'v20.14.0'

      - script: |
         npm install
         npm run build
        displayName: 'Install Dependencies and Build'

      - task: ArchiveFiles@2
        displayName: 'Archive Build Artifacts'
        inputs:
          rootFolderOrFile: '$(packageDir)' 
          includeRootFolder: false
          archiveType: 'zip'
          achiveFile: '$(Build.ArtifactStagingDirectory)/$(appName).zip'
          replaceExistingArchive: true
        
      - task: PublishBuildArtifacts@1 
        displayName: 'Publish Build Artifacts'
        inputs: 
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'
  
  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
    - deployment: Deploy
      displayName: 'Deploy to Azure App Service'
      environment: 'Production'
      strategy:
        runOnce:
          deploy: 
            steps: 
            - task: DownloadBuildArtifacts@0
              displayName: 'Download Build Artifacts'
              inputs: 
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: AzureWebApp@1
              displayName: 'Deploy to Azure Web App'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: 'webAppLinux' # Use 'webApp' for Windows App Services
                appName: '$(appName)'
                package: '$(System.ArtifactsDirectory)/drop/$(appName).zip'
